"""Write docs/REPO_MAP.md: every Python module, its ring, and the first line of its docstring.

A reader arriving cold -- a person or an agent -- needs one page that says what each file is
for before opening any of them. Hand-written maps go stale (CLAUDE.md's repository map has
been corrected three times for exactly that), so this one is generated from the code itself:
the ring comes from `checker/rings.py`, the purpose from the module's own docstring.

A module with no docstring is listed as "(no docstring)" rather than described by guesswork.

    python3 scripts/repo_map.py           # rewrite docs/REPO_MAP.md
    python3 scripts/repo_map.py --check   # exit 1 if the file is out of date
    python3 scripts/repo_map.py --test    # self-test
"""
from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "REPO_MAP.md"

# Top-level areas, in the order a reader should meet them.
AREAS = [
    ("applicability.py", "Root: the applicability evaluator"),
    ("checker", "checker/: the engine (legal core, retrieval, verification, sources)"),
    ("agents", "agents/: the agent runtime (typed plans, one file per intent)"),
    ("gateway", "gateway/: the HTTP, MCP and CLI surface, auth, tenancy, queue"),
    ("backend", "backend/: model cost and budget"),
    ("eval", "eval/: gold set and evaluation harnesses"),
    ("scripts", "scripts/: ingestion, verification, servers and the test gate"),
]

RING_LABEL = {0: "R0 legal core", 1: "R1 bookmark", 2: "R2 feeds", 3: "R3 inference"}


def tracked_python() -> list[str]:
    out = subprocess.check_output(["git", "ls-files", "*.py"], cwd=ROOT, text=True)
    # `set`, not just `sorted`: during a merge `git ls-files` prints a conflicted path
    # once per stage (1, 2, 3), so an unmerged module would otherwise be listed three
    # times and counted three times. Dedup makes the map deterministic mid-merge.
    return sorted({p for p in out.split("\n") if p})


def first_line(path: Path) -> str:
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    except (SyntaxError, UnicodeDecodeError):
        return "(could not parse)"
    if not doc:
        return "(no docstring)"
    return doc.strip().split("\n")[0].strip().replace("|", "\\|")


def ring_label(rel: str) -> str:
    sys.path.insert(0, str(ROOT))
    try:
        from checker.rings import ring_of
    finally:
        sys.path.pop(0)
    ring = ring_of(rel)
    return RING_LABEL.get(ring, "") if ring is not None else ""


def area_of(rel: str) -> str | None:
    for key, _ in AREAS:
        if rel == key or rel.startswith(key + "/"):
            return key
    return None


def render(files: list[str]) -> str:
    lines = [
        "# Repository map (generated)",
        "",
        "Generated by `python3 scripts/repo_map.py` from each module's own docstring and "
        "`checker/rings.py`. **Do not edit by hand**: change the docstring and regenerate.",
        "Start with [START_HERE.md](START_HERE.md); this page is the index behind it.",
        "",
        "Ring column: which layer of the one-way firewall a module is registered in "
        "(`checker/rings.py`). Blank means unregistered, which is normal for tools and tests.",
        "",
    ]
    for key, title in AREAS:
        rows = [f for f in files if area_of(f) == key]
        if not rows:
            continue
        lines += [f"## {title}", "", "| File | Ring | Purpose |", "|---|---|---|"]
        for rel in rows:
            lines.append(f"| `{rel}` | {ring_label(rel)} | {first_line(ROOT / rel)} |")
        lines.append("")
    lines.append(f"{len([f for f in files if area_of(f)])} modules listed.")
    return "\n".join(lines) + "\n"


def check_current() -> tuple[bool, str]:
    """(is the committed map current, a line the HARNESS can read).

    The message carries a `N/N passed` count on purpose. `scripts/run_tests.sh` rule (a)
    treats a suite that prints no count line as a FAILURE -- deliberately, because eight
    modules once defined `_test()` without raising and their failures never reached the
    exit code. So `--check` printing only prose would have been marked nocount=FAIL on the
    runs where it PASSED, and the obvious response to that is to pull it back out of the
    gate, which is how a staleness check stops existing.
    """
    body = render(tracked_python())
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if current == body:
        return True, "1/1 passed — docs/REPO_MAP.md is current"
    return False, ("0/1 passed — docs/REPO_MAP.md is out of date: run "
                   "python3 scripts/repo_map.py")


def _test() -> None:
    passed = failed = 0

    def check(cond: bool, label: str) -> None:
        nonlocal passed, failed
        if cond:
            passed += 1
        else:
            failed += 1
            print(f"  [FAIL] {label}")

    files = tracked_python()
    text = render(files)
    check(len(files) > 100, f"the walk finds the codebase ({len(files)} files)")
    check(len(files) == len(set(files)),
          "the module list has no duplicates -- git ls-files prints a conflicted path "
          "once per stage, and the map must not list or count it three times")
    check("`checker/scope.py`" in text, "the scope register is listed")
    check("`gateway/verbs.py`" in text, "the verb table is listed")
    check("R0 legal core" in text, "ring labels come from checker/rings.py")
    check(text == render(files), "the output is deterministic")
    check(first_line(ROOT / "checker" / "scope.py") != "(no docstring)",
          "a documented module shows its purpose")

    # ── the committed map is current ────────────────────────────────────────
    ok, line = check_current()
    check(ok, f"docs/REPO_MAP.md matches the code ({line})")
    # And the message `--check` prints must carry a count in BOTH states, or the harness
    # marks the passing run as nocount=FAIL. Asserted rather than assumed: this is the
    # property that lets the check live in the gate at all.
    for text in (check_current()[1],
                 "0/1 passed — docs/REPO_MAP.md is out of date: run "
                 "python3 scripts/repo_map.py"):
        import re as _re
        check(bool(_re.search(r"\d+/\d+ passed", text)),
              f"--check prints a count line the harness can read ({text[:40]!r})")
    check("1/1" in check_current()[1] or "0/1" in check_current()[1],
          "...and the count reflects the verdict rather than being decoration")

    # Newly-added modules must appear. A map that silently omits a file is the stale map
    # this generator replaced.
    text_now = render(tracked_python())
    for rel in ("agents/intake.py", "gateway/envelope.py"):
        if (ROOT / rel).exists():
            check(f"`{rel}`" in text_now, f"{rel} is listed")

    print(f"{passed}/{passed + failed} passed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    if "--test" in sys.argv:
        _test()
    body = render(tracked_python())
    if "--check" in sys.argv:
        ok, line = check_current()
        print(line)
        sys.exit(0 if ok else 1)
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
