#!/usr/bin/env python3
"""BM25 over a vault's chunks, per tenant, with each chunk told where it came from.

V1. Twenty thousand documents are only useful if a lawyer can find the clause they half
remember. This is the retrieval half: chunk a document, give each chunk a sentence of
CONTEXT, score with Okapi BM25.

Written from the standard library. CLAUDE.md requires a stated reason for a new
dependency, and BM25 is forty lines of arithmetic -- the reason would have to be "I did
not want to write forty lines", which is not one.

## Contextual chunks, and why the plain ones fail

A chunk reading "The term is five years." matches nothing a lawyer would type. The same
chunk indexed as

    Petrichor NDA (nda), clause 2 Term. The term is five years.

matches "NDA term", "how long is the Petrichor confidentiality obligation", and "five
years". The context is OUR OWN sentence, built from facts we already hold -- the document's
name, its class, the nearest heading -- and it is prefixed for INDEXING only. What is shown
back is the chunk's own text, because the context is ours and the quote must be theirs.

`scripts/vault_retrieval_bakeoff.py` measures what that is worth, before and after, on the
same queries. The number is not asserted here; it is measured there, because a retrieval
claim in a docstring is a claim nobody re-runs.

## A search says what it COULD NOT look at

A vault where 300 of 20,000 documents are scans with OCR blocked will answer every query
from 19,700 documents and look complete. `Results.unsearchable` carries that count, so a
nil return can be told from a nil return with three hundred unread files behind it.

## The index never mixes tenants

`Index.build` takes rows that are already tenant-scoped by the store's RLS, and refuses a
mixed batch outright rather than trusting the caller. One leak here is one firm's
documents answering another firm's question.

Run: PYTHONPATH=. python3 checker/vault_search.py --test
"""
from __future__ import annotations

import math
import re
from collections import Counter
from dataclasses import dataclass, field

__all__ = ["K1", "B", "CHUNK_CHARS", "tokenize", "chunk", "contextualise", "Index",
           "Hit", "Results", "SearchError"]

# Okapi BM25's usual constants. Not tuned: tuning them against a corpus we have not
# measured would be fitting to a guess.
K1 = 1.5
B = 0.75

# Characters per chunk. A clause is usually a paragraph; a chunk much larger dilutes the
# term frequencies that make BM25 work, and much smaller loses the sentence that gives a
# clause its meaning.
CHUNK_CHARS = 900

_WORD = re.compile(r"[a-z0-9]+")
# A heading, for context: a numbered clause or an ALL-CAPS line.
_HEADING = re.compile(r"^\s*(?:(\d+(?:\.\d+)*)\.?\s+)?([A-Z][A-Za-z ]{2,40})\s*$")


class SearchError(ValueError):
    """A search that cannot be run. Never an empty result standing in for one."""


def tokenize(text: str) -> list[str]:
    return _WORD.findall(str(text or "").lower())


def chunk(text: str, *, size: int = CHUNK_CHARS) -> list[str]:
    """Split on blank lines, then pack to `size`. Never mid-word.

    Paragraph-first because a contract's unit of meaning is the clause, and a fixed-width
    window cuts one in half at exactly the point a reader needs.
    """
    if size <= 0:
        raise SearchError(f"a chunk size of {size} splits nothing")
    paras = [p.strip() for p in re.split(r"\n\s*\n", str(text or "")) if p.strip()]
    out: list[str] = []
    buf = ""
    for para in paras:
        if buf and len(buf) + len(para) + 2 > size:
            out.append(buf)
            buf = para
        elif len(para) > size:
            # One huge paragraph: break on whitespace, never mid-word.
            if buf:
                out.append(buf)
                buf = ""
            words, line = para.split(), ""
            for w in words:
                if line and len(line) + len(w) + 1 > size:
                    out.append(line)
                    line = w
                else:
                    line = f"{line} {w}".strip()
            if line:
                buf = line
        else:
            buf = f"{buf}\n\n{para}".strip()
    if buf:
        out.append(buf)
    return out


def _heading_for(text: str) -> str:
    for line in str(text or "").splitlines():
        m = _HEADING.match(line)
        if m:
            return " ".join(x for x in (m.group(1), m.group(2)) if x).strip()
    return ""


def contextualise(chunk_text: str, *, name: str, doc_class: str = "") -> str:
    """The sentence prefixed to a chunk FOR INDEXING ONLY.

    Built from facts we already hold. Nothing here is generated by a model, so there is
    nothing to verify and nothing that can be wrong in a way a quote would hide.
    """
    bits = [str(name or "").strip()]
    if doc_class and doc_class != "unknown":
        bits.append(f"({doc_class})")
    heading = _heading_for(chunk_text)
    if heading:
        bits.append(f"clause {heading}")
    prefix = " ".join(b for b in bits if b).strip()
    return f"{prefix}. {chunk_text}" if prefix else str(chunk_text or "")


@dataclass(frozen=True)
class Hit:
    document_id: str
    ordinal: int
    score: float
    text: str                 # the chunk's OWN text, never the context we prefixed
    name: str = ""
    doc_class: str = ""


@dataclass(frozen=True)
class Results:
    hits: tuple = ()
    searched_documents: int = 0
    searched_chunks: int = 0
    unsearchable: int = 0           # documents whose text could not be read
    note: str = ""

    def to_dict(self) -> dict:
        return {"hits": [{"document_id": h.document_id, "ordinal": h.ordinal,
                          "score": h.score, "text": h.text, "name": h.name,
                          "doc_class": h.doc_class} for h in self.hits],
                "searched_documents": self.searched_documents,
                "searched_chunks": self.searched_chunks,
                "unsearchable": self.unsearchable, "note": self.note}


@dataclass
class Index:
    """A tenant's chunks, scored by BM25. Build once, query many times."""
    tenant_id: str = ""
    docs: list = field(default_factory=list)        # (document_id, ordinal, own text, meta)
    _tokens: list = field(default_factory=list)
    _df: Counter = field(default_factory=Counter)
    _avg_len: float = 0.0
    unsearchable: int = 0

    @staticmethod
    def build(rows, *, tenant_id: str = "", unsearchable: int = 0,
              contextual: bool = True) -> "Index":
        """`rows` are {document_id, ordinal, text, name, doc_class, tenant_id}.

        A row from another tenant RAISES. The store's RLS should make that impossible, and
        this refuses anyway: one leak here is one firm's documents answering another
        firm's question, and a defence that relies on a single layer is one bug from being
        no defence.
        """
        idx = Index(tenant_id=tenant_id, unsearchable=int(unsearchable))
        for r in rows or ():
            rt = str(r.get("tenant_id") or tenant_id or "")
            if tenant_id and rt and rt != tenant_id:
                raise SearchError(
                    f"chunk from tenant {rt} in an index for {tenant_id}: an index that "
                    f"mixes tenants answers one firm's question from another's documents")
            own = str(r.get("text") or "")
            indexed = (contextualise(own, name=str(r.get("name") or ""),
                                     doc_class=str(r.get("doc_class") or ""))
                       if contextual else own)
            toks = tokenize(indexed)
            idx.docs.append((str(r.get("document_id") or ""), int(r.get("ordinal") or 0),
                             own, {"name": r.get("name") or "",
                                   "doc_class": r.get("doc_class") or ""}))
            idx._tokens.append(Counter(toks))
            idx._df.update(set(toks))
        lengths = [sum(c.values()) for c in idx._tokens]
        idx._avg_len = (sum(lengths) / len(lengths)) if lengths else 0.0
        return idx

    def search(self, query: str, *, limit: int = 10) -> Results:
        terms = tokenize(query)
        n = len(self.docs)
        docs_seen = len({d[0] for d in self.docs})
        if not terms:
            return Results((), docs_seen, n, self.unsearchable,
                           "the query has no searchable words")
        if not n:
            return Results((), 0, 0, self.unsearchable,
                           "nothing is indexed for this tenant. That is not 'no document "
                           "matches': it is 'there is nothing to match against'"
                           + (f", and {self.unsearchable} document(s) could not be read"
                              if self.unsearchable else ""))
        scored = []
        for i, (doc_id, ordinal, own, meta) in enumerate(self.docs):
            tf = self._tokens[i]
            length = sum(tf.values()) or 1
            score = 0.0
            for t in terms:
                f = tf.get(t, 0)
                if not f:
                    continue
                df = self._df.get(t, 0)
                idf = math.log(1 + (n - df + 0.5) / (df + 0.5))
                score += idf * (f * (K1 + 1)) / (
                    f + K1 * (1 - B + B * length / (self._avg_len or 1)))
            if score > 0:
                scored.append(Hit(doc_id, ordinal, round(score, 4), own,
                                  str(meta.get("name") or ""),
                                  str(meta.get("doc_class") or "")))
        scored.sort(key=lambda h: (-h.score, h.document_id, h.ordinal))
        note = f"{len(scored)} chunk(s) matched out of {n}"
        if self.unsearchable:
            note += (f". {self.unsearchable} document(s) could NOT be searched -- their "
                     f"text was never extracted, so this result is from a part of the "
                     f"vault, not all of it")
        return Results(tuple(scored[:limit]), docs_seen, n, self.unsearchable, note)


def _test() -> int:
    ok = fail = 0

    def check(cond: bool, label: str) -> None:
        nonlocal ok, fail
        if cond:
            ok += 1
            print(f"  [PASS] {label}")
        else:
            fail += 1
            print(f"  [FAIL] {label}")

    print("vault_search")

    ROWS = [
        {"document_id": "d1", "ordinal": 0, "tenant_id": "t1", "name": "Petrichor NDA",
         "doc_class": "nda",
         "text": "2. Term\n\nThe term is five years from the Effective Date."},
        {"document_id": "d2", "ordinal": 0, "tenant_id": "t1", "name": "Office Lease",
         "doc_class": "lease", "text": "Rent shall be paid monthly in advance."},
        {"document_id": "d3", "ordinal": 0, "tenant_id": "t1", "name": "Vendor MSA",
         "doc_class": "services_agreement",
         "text": "The supplier shall indemnify the customer against third party claims."},
    ]

    # ── tokenising and chunking ────────────────────────────────────────────
    check(tokenize("Clause 4.2 -- Indemnity!") == ["clause", "4", "2", "indemnity"],
          f"tokenising splits on non-alphanumerics ({tokenize('Clause 4.2 -- Indemnity!')})")
    check(tokenize("") == [], "empty text tokenises to nothing")
    paras = chunk("A" * 10 + "\n\n" + "B" * 10, size=900)
    check(len(paras) == 1, "two short paragraphs pack into one chunk")
    big = chunk("word " * 500, size=200)
    check(len(big) > 1 and all(len(c) <= 220 for c in big),
          f"a long paragraph splits, and near the size ({[len(c) for c in big][:4]})")
    check(all(not c.startswith(" ") and "  " not in c for c in big),
          "...on whitespace, never mid-word")
    check(chunk("") == [], "no text is no chunks")
    try:
        chunk("x", size=0)
        check(False, "a zero chunk size raises")
    except SearchError:
        check(True, "a zero chunk size RAISES rather than looping or returning nothing")

    # ── context is ours, the quote is theirs ───────────────────────────────
    ctx = contextualise("The term is five years.", name="Petrichor NDA", doc_class="nda")
    check(ctx.startswith("Petrichor NDA (nda)") and "five years" in ctx,
          f"a chunk is indexed with its document's name and class ({ctx[:40]})")
    check("clause 2 Term" in contextualise("2. Term\n\nThe term is five years.",
                                           name="X", doc_class="nda"),
          "...and the nearest heading when there is one")
    check(contextualise("body", name="", doc_class="") == "body",
          "with nothing to say, the chunk is indexed as itself rather than with an empty "
          "prefix")

    ix = Index.build(ROWS, tenant_id="t1")
    r = ix.search("NDA term")
    check(r.hits and r.hits[0].document_id == "d1",
          f"a query naming the document and the clause finds it ({[h.document_id for h in r.hits]})")
    check(r.hits[0].text.startswith("2. Term"),
          f"**what is shown is the chunk's OWN text**, not the context we prefixed: the "
          f"context is ours and the quote must be theirs ({r.hits[0].text[:18]!r})")
    check("Petrichor NDA" not in r.hits[0].text,
          "...so our sentence never appears inside a quoted passage")

    # ── contextual beats plain on the query a lawyer actually types ────────
    plain = Index.build(ROWS, tenant_id="t1", contextual=False).search("NDA term")
    check(r.hits[0].score > (plain.hits[0].score if plain.hits else 0),
          f"the contextual index scores higher on 'NDA term' "
          f"({r.hits[0].score} vs {plain.hits[0].score if plain.hits else 0})")
    plain_only = Index.build(ROWS, tenant_id="t1", contextual=False).search("Petrichor")
    check(not plain_only.hits and Index.build(ROWS, tenant_id="t1"
                                              ).search("Petrichor").hits,
          "a query for the document's NAME finds nothing in a plain index and finds it in "
          "a contextual one -- the case the whole technique exists for")

    # ── the index never mixes tenants ──────────────────────────────────────
    try:
        Index.build(ROWS + [{"document_id": "x", "ordinal": 0, "tenant_id": "t2",
                             "text": "another firm's contract", "name": "Other"}],
                    tenant_id="t1")
        check(False, "a foreign tenant's chunk raises")
    except SearchError as e:
        check("mixes tenants" in str(e),
              "**a chunk from another tenant RAISES** -- the store's RLS should make it "
              "impossible and this refuses anyway: a defence that relies on one layer is "
              "one bug from being no defence")

    # ── a search says what it could not look at ────────────────────────────
    blind = Index.build(ROWS, tenant_id="t1", unsearchable=300).search("indemnify")
    check(blind.hits and blind.unsearchable == 300,
          "a search still answers with unreadable documents in the vault")
    check("not all of it" in blind.note,
          f"...and SAYS it searched part of the vault: 300 scans with OCR blocked would "
          f"otherwise answer every query from the rest and look complete "
          f"({blind.note[-60:]})")

    empty = Index.build([], tenant_id="t1").search("anything")
    check(not empty.hits and "nothing to match against" in empty.note,
          f"an empty index says 'there is nothing to match against', NOT 'no document "
          f"matches' -- which would read as an absence we had checked for ({empty.note[:46]})")
    check(ix.search("").note and not ix.search("").hits,
          "a query with no searchable words says so")
    check(not ix.search("zzzzz").hits,
          "a term in no document returns nothing")

    # ── BM25 itself ────────────────────────────────────────────────────────
    check((K1, B) == (1.5, 0.75), "the BM25 constants are the usual ones, untuned")
    many = Index.build(
        [{"document_id": f"d{i}", "ordinal": 0, "tenant_id": "t1", "name": f"Doc {i}",
          "text": "indemnity clause here"} for i in range(50)]
        + [{"document_id": "rare", "ordinal": 0, "tenant_id": "t1", "name": "Rare",
            "text": "a novation clause here"}], tenant_id="t1")
    res = many.search("novation indemnity")
    check(res.hits[0].document_id == "rare",
          f"a RARE term outranks a common one: that is what idf buys, and a vault of one "
          f"contract type is all common terms ({res.hits[0].document_id})")
    check(len(many.search("indemnity", limit=3).hits) == 3,
          "the limit is honoured")
    import inspect as _inspect
    mods = {n.split(".")[0] for n in dir(_inspect.getmodule(Index))}
    check("rank_bm25" not in mods and "sklearn" not in mods,
          "BM25 is forty lines of arithmetic from the standard library: a dependency "
          "would need a better reason than not wanting to write them")

    print(f"\n{ok}/{ok + fail} passed")
    return 1 if fail else 0


if __name__ == "__main__":
    import sys
    if "--test" in sys.argv:
        raise SystemExit(_test())
    print(__doc__)
